TITAN_HONORVIEW_HP = "HP";
TITAN_HONORVIEW_HK = "HK";
TITAN_HONORVIEW_HCURRENCY = "Honor Currency";
TITAN_HONORVIEW_HKILLS = "Honorable Kills";
TITAN_HONORVIEW_HPOINTS = "Honor Points";
TITAN_HONORVIEW_HBONUS = "Bonus Honor";
TITAN_HONORVIEW_HTOTAL = "Total Honor";
TITAN_HONORVIEW_DEATHS = "Deaths";
TITAN_HONORVIEW_KBLOWS = "Killing Blows";
TITAN_HONORVIEW_LIFETIME = "Lifetime";
TITAN_HONORVIEW_TODAY = "Today";
TITAN_HONORVIEW_YESTERDAY = "Yesterday";

TITAN_HONORVIEW_BGCURRENT = "Current Battleground";
TITAN_HONORVIEW_BGRECENT = "Recent Battlegrounds";
TITAN_HONORVIEW_CUMULATIVE_STATS = "Cumulative Stats"
TITAN_HONORVIEW_STATS = " Stats";

TITAN_HONORVIEW_MATCHESWON = "Matches Won";
TITAN_HONORVIEW_HAVERAGES = "Honor Averages";
TITAN_HONORVIEW_AVGQUEUE = "Average Queue Time";
TITAN_HONORVIEW_PLAYTIME = "Total Play Time";

TITAN_HONORVIEW_MENU_SHOW_LIFETIME = "Show Lifetime Honor";
TITAN_HONORVIEW_MENU_SHOW_TODAY = "Show Today's Honor";
TITAN_HONORVIEW_MENU_SHOW_YESTERDAY = "Show Yesterday's Honor";
TITAN_HONORVIEW_MENU_SHOW_RECENTDATA = "Show Recent Battleground Data";
TITAN_HONORVIEW_MENU_SHOW_CUMULATIVESTATS = "Show Cumulative Stats";
TITAN_HONORVIEW_MENU_SHOW_WSGSTATS = "Show Warsong Gulch Stats";
TITAN_HONORVIEW_MENU_SHOW_ABSTATS = "Show Arathi Basin Stats";
TITAN_HONORVIEW_MENU_SHOW_AVSTATS = "Show Alterac Valley Stats";
TITAN_HONORVIEW_MENU_SHOW_EOSSTATS = "Show Eye of the Storm Stats";

TITAN_HONORVIEW_MENU_RESET_MATCHLIST = "Reset Match List";
TITAN_HONORVIEW_MENU_RESET_BGSTATS = "Reset Battleground Stats";
TITAN_HONORVIEW_MENU_RESET_ALL = "Reset All";

TITAN_HONORVIEW_MENU_DEBUG = "Debug";

